version: '3'

services:
  frontend:
    build: ./
    tty: true
    command: bash -c "npm install && npm run start:dev"
    environment:
      - PORT=3008
    ports:
      - "3008:3008"
    volumes:
      - ./:/react-plaid-link-button
